# Generated by Django 3.2.7 on 2021-09-14 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(db_column='USER_IS', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='USER_NAME', max_length=20)),
                ('user_email', models.CharField(db_column='USER_EMAIL', max_length=30, unique=True)),
                ('password', models.CharField(db_column='PASSWORD', max_length=30, unique=True)),
                ('mobile', models.CharField(blank=True, db_column='MOBILE', max_length=12, null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=100, null=True)),
                ('is_admin', models.BooleanField(blank=True, db_column='IS_ADMIN', default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_product_id', models.AutoField(db_column='CART_PRODUCT_ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='QUANTITY')),
                ('products', models.ForeignKey(db_column='PRODUCTS', on_delete=django.db.models.deletion.CASCADE, related_name='CART', to='masters.products')),
                ('user', models.ForeignKey(db_column='USER', on_delete=django.db.models.deletion.CASCADE, related_name='CART', to='users.users')),
            ],
        ),
    ]
