# Generated by Django 3.2.7 on 2021-09-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20210918_0917'),
        ('users', '0003_cart_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('masters.orders',),
        ),
    ]
