# Generated by Django 3.2.7 on 2021-09-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_orderproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, db_column='ADDED_DATE', null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(blank=True, db_column='IS_ACTIVE', null=True),
        ),
    ]
