# Generated by Django 3.2.7 on 2021-09-18 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart_size'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='masterUser',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, db_column='USERS', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ORDERS', to='users.users'),
        ),
    ]
