# Generated by Django 3.2.7 on 2021-09-20 10:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20210920_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cart_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, db_column='CART_ID', max_length=10, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
