# Generated by Django 3.2.7 on 2021-09-21 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0006_alter_orders_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('mobile', models.CharField(db_column='MOBILE', max_length=10)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=500, null=True)),
                ('user', models.ForeignKey(db_column='USER', on_delete=django.db.models.deletion.CASCADE, related_name='EXTENDUSER', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MST_EXTENDUSER',
            },
        ),
    ]
