# Generated by Django 3.2.7 on 2021-09-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_extenduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendUser',
        ),
    ]
