# Generated by Django 3.2.7 on 2021-09-21 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phone', models.CharField(db_column='PHONE', max_length=10, unique=True)),
                ('address', models.CharField(db_column='ADDRESS', max_length=500)),
                ('user', models.ForeignKey(db_column='USER', on_delete=django.db.models.deletion.CASCADE, related_name='EXTENDUSER', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtendUserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('login.extenduser',),
        ),
    ]
